Dictionaries - add support for migrations
realm/realm-java pull request #7343
Opened 2021-03-11 08:35 UTC by edualonso

2021-03-11 11:18 UTC, clementetb requested changes
Great job 👏👏👏 ! Added some minor cr.

2021-03-11 11:18 UTC, clementetb commented on realm/realm-library/src/androidTest/kotlin/io/realm/DictionaryMigrationTests.kt
> + * Copyright 2020 Realm Inc.
```suggestion
 * Copyright 2021 Realm Inc.
```

2021-03-11 11:18 UTC, clementetb commented on realm/realm-library/src/androidTest/kotlin/io/realm/GenericTester.kt
> + * Copyright 2020 Realm Inc.
```suggestion
 * Copyright 2021 Realm Inc.
```

2021-03-11 11:18 UTC, clementetb commented on realm/realm-library/src/androidTest/kotlin/io/realm/entities/DictionaryClass.kt
> + * Copyright 2020 Realm Inc.
```suggestion
 * Copyright 2021 Realm Inc.
```

2021-03-11 11:18 UTC, clementetb commented on realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
>      static final Map<Class<?>, FieldMetaData> getSupportedSimpleFields() {
The function name is misleading, it is just for lists. We could directly access the `SUPPORTED_LIST_SIMPLE_FIELDS ` as you do with `SUPPORTED_DICTIONARY_SIMPLE_FIELDS`.

2021-03-13 20:11 UTC, edualonso commented
All comments have been addressed. I will merge this Monday morning If you guys have no more comments.

2021-03-15 08:45 UTC, rorbech approved these changes
I am not familiar with the dynamic schema api, but LGTM.

2021-03-15 08:45 UTC, rorbech commented on realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
> +        Map<Class<?>, FieldMetaData> listMap = new HashMap<>();
Again this looks like candidates for refactoring into the field type interface for #7320

2021-03-15 17:18 UTC, merged